#!/usr/bin/env bash
# Ensure propagation of exit codes
set -eu
# We must reference the modfile without changing the working directory
SCRIPT_LOCATION="$(dirname $(readlink -f -- "${0}"))"
# Enable script debugging
DEBUG_GOTOOL_SCRIPT="${DEBUG_GOTOOL_SCRIPT:-}"
[ -z "${DEBUG_GOTOOL_SCRIPT:-}" ] || {
  set -x
}
# Call appropriate go tool and pass all argument directly to the tool
go tool --modfile=${SCRIPT_LOCATION}/gow.mod gow "${@}"
